[project]
name = "rtf-to-txt"
version = "0.1.0"
description = "RTF to TXT conversion service"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aio-pika>=9.5.5",
    "minio>=7.2.15",
    "python-dotenv>=1.1.0",
    "striprtf>=0.0.26",
]
